# Site settings
title: Paulo Serôdio
description:
    Block style: !!seq
        - Mercury   # Rotates - no light/dark sides.
        - Venus     # Deadliest. Aptly named.
url: 'https://pamato.github.io/personal-webpage/'
baseurl: '/personal-webpage/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Paulo M Serôdio'
  email: paulo.serodio@sociology.ox.ac.uk
  twitter_username: p_serodio
  facebook_username: paulo.serodio
  github_username:  pamato
  linkedin_username:  paulomserodio

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
include: ["_pages"]
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
